[[SCIP_PaPILO]]
arch = "aarch64"
git-tree-sha1 = "af5b58935e7660a0cddb12d8aa6b8cb43213d200"
libgfortran_version = "5.0.0"
os = "macos"

    [[SCIP_PaPILO.download]]
    sha256 = "a4d3beb7f55406b6893c8c29411396009b54f17a1047528a89c08e9ee4afb807"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SCIP_PaPILO]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54e5ff351e7b040cd4c9626be879f09e46999bec"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "c8024a96bbb62b9428399ad1587fea9ebe3323971c2bdd7b2bac1506afcc126d"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "347f210ce5da6aa66826044ca369d98dd370646e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "5d573c54205563062200bc249528bfe9ba42004a66f8c1eacd67d5fed558fd0d"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b373675612ca48a9d746487bd233c54d9d4a5b4a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "fd18c4091becf4c5496f1a61477d899dc40e109dc72aed9dd54c03ada5077104"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3845c3c7b6c3177881c41ee537074c571abc876e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "9cd9014f9b16ad121e832f84f6d0e2cf6b1c40321605ba55d8f77e46a7de10c5"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.armv6l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5014fa646c0f1b3418169a0eef7d7553e7172c1c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "be1115ede784c684868554e965fbe6e71ddab1cc859dcaf2318b271f0605e05f"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4217cdc638dd913087860834678a3b0790087d4c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "09a7c1008eb94006f005699e0df46800d2031e125efbb868aef6c44f97008112"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.armv7l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d2f9ffd625a212485f9b2b965ea89054064b0d7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "23bebd158270c9f05241df186ca14fe6898ea22e5946f957ce6280ccc9902720"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2e9482f5e68985b0a5431bcbc6ef757318a1d96"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "c26cd29d30dd42b1ea0519d68d409f75c9b9c9b9d7fea6ace7a781477680f75f"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.i686-linux-musl-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "473fd27b6e5847893803b95f129cd673e9b87a50"
libgfortran_version = "5.0.0"
os = "windows"

    [[SCIP_PaPILO.download]]
    sha256 = "43ba1b4c7cc955123f26e6a097ea1f7372f2d4bfcd706aab58fd0c9fe1447b8c"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf44e7b851e72911b5aaf6d858d30971b98564a0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "7638ff3266cd4e47971e303809cf2b1c41ff47d2a8571e766bc7eb1752e4978d"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
git-tree-sha1 = "0649f0837f273ec9e314a1adfed660b878ed6ca0"
libgfortran_version = "5.0.0"
os = "macos"

    [[SCIP_PaPILO.download]]
    sha256 = "01a96d3f567aa4175434dd82190fe7005915ccb63d1ee1099e322b87fe48ca00"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64ef910fe67dbb745966c477bed7dbf1dc70fff8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "a7e7fcf9440ff7d3652a55430a9fc60a325cfe4ad65d66cf8c0cc65e4ce2b993"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83aeb17de5e508e526e4d61b8d51f0d013038380"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "387d235e38cd9c9273436fc8f7f3a33f703fb1ec917d2fe56237f895e3054fd3"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
git-tree-sha1 = "f51a59fae7bf20f4a40aad8d1edc6ed9c776a851"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SCIP_PaPILO.download]]
    sha256 = "80405f40b5ea1a84f56eec5b23070d70a6c0810ae42b47b58c2b78c4ce8f67b0"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec65893e47a781195eacaeba56deeb6682163dfe"
libgfortran_version = "5.0.0"
os = "windows"

    [[SCIP_PaPILO.download]]
    sha256 = "ed3dece5b37cd6c671ccd3c51491142dc2a732f24dd4cbbfa8a5d053b9805045"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.0+0/SCIP_PaPILO.v1000.0.0.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
