[[SCIP_PaPILO]]
arch = "aarch64"
git-tree-sha1 = "261d824627b2c53663e71b6ec0393d1a9d9324f2"
libgfortran_version = "5.0.0"
os = "macos"

    [[SCIP_PaPILO.download]]
    sha256 = "139beeec1d5904ab882d05b82a5cd944a529ac700093d3146b4232b72db7bd4c"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SCIP_PaPILO]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c10c31fd7c96cc3aea2156d4b811ed1896d2cdd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "9a13be5fe46e4bd6f19a3f26c27bf2ee1b4d060b2402710d72adf1df66adbdb9"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f593935b269b67c6552caaad805fdd59343ded90"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "e43caaf7b29431b733e4675544eb8afcb59beb6eb4e7fd44027a2835c74bfa7b"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e1d126b350b785bd36ac4933cb04e72eec28ea9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "12f79cb2d6e259142e28aeb32ce40b8bc838e58a9978cd71fb0c358af9217b94"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3b3b2757d7346c759371a96922494450849ce0d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "64db6c6cb84b0c7979911b685cfd747811bfb6392063f40bb9b862c5aaa8569f"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.armv6l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "148e811790e51c956a496af374f9f0830702d3c9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "c1af244edf94b070c696673d91bc6a6f884212aeff64bc05f90d547c26d42822"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab6410588f44a849a1eb4ad8dd181a659d94a238"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "47791075d781893ed38e361c29c7b5c1a8c18238f997f7a1cce34a114b28f771"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.armv7l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7002c3953e8a418c63f226da308caff0e107ebdc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "ea9969b71285dfab0458dc13194985f3a65b00f77a2294b2448cbb218aeb0334"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dda3de401d0dea7b54bf37c0e3b1d5b9351fff2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "4e09ee32f77e8a6def4e98e7e851aa4fa7c289785f10961dab11905e204d9859"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.i686-linux-musl-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6be9bebfbc9680a11745cb8571285b0989fd284b"
libgfortran_version = "5.0.0"
os = "windows"

    [[SCIP_PaPILO.download]]
    sha256 = "9cc9c118c3640bdb685cd6971231cbdff9d34b9082ac6cc7498c6abb66496e25"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ece25b1d30d6a31cc97a7a652796eb746bb33e9a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "aa245f32a29d61f433ef34c6728226c00cf62549cf7e1268f05ba3e0e9e2dbf6"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
git-tree-sha1 = "1bb9c17059e699667281026da9f84d4e624ae25e"
libgfortran_version = "5.0.0"
os = "macos"

    [[SCIP_PaPILO.download]]
    sha256 = "4889d8698aea9fdc54d2edfcd99a73d0f411208e57f1d192494d6d152abf58a7"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0004f9e1a144045568d337f726030bc46a0c532"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "2be76a42e84fcbcfec8f1142cc528839fcf892f32db04f7f98e73454c0a099b4"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d82b5db1990109ed34a94db5f6fb3a116f8a7c45"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "845b530ab88f6217320b2fd31aae2b1582701f32011de2ad1fe159734aba6ebf"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
git-tree-sha1 = "e794011281935e625106e40842435fb81c5c57da"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SCIP_PaPILO.download]]
    sha256 = "666b82846d6f8f261300c4f3b207609e8ce8d6d66540a653c175e7ee89aabdff"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b768e04e1946ad3f510841a44eeaa448f3869e50"
libgfortran_version = "5.0.0"
os = "windows"

    [[SCIP_PaPILO.download]]
    sha256 = "28da1c0c8446d186b97febe03e5125461f4e2c8ce2562b66392fdda35f13fa01"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v900.200.400+0/SCIP_PaPILO.v900.200.400.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
